version: 2.1


common: &common
  working_directory: ~/project
  steps:
    - checkout
    - restore_cache:
        keys:
          - v3-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user "tox<4"
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: v3-deps-{{ .Environment.CIRCLE_JOB }}-{{ checksum "tox.ini" }}


jobs:
  py38:
    <<: *common
    docker:
      - image: circleci/python:3.8
        environment:
          TOXENV=py38-dj30,py38-dj31

workflows:
  test:
    jobs:
      - py38
